FROM ubuntu:22.10

# Python is necessary for ARM platform
RUN apt -y update
RUN apt -y install nodejs yarnpkg python3

COPY signFeed/package.json signFeed/yarn.lock signFeed/signfeed-cli.js /root/signFeed/
WORKDIR /root/signFeed
RUN yarn

RUN chmod a+x /root

RUN mkdir /private
VOLUME /private
# EXPOSE 1633
