FROM nginx:latest

# COPY proxy.conf /etc/nginx/proxy.conf
COPY proxy.conf /etc/nginx/sites-available/
RUN mkdir /etc/nginx/sites-enabled/
RUN ln -s ../sites-available/proxy.conf /etc/nginx/sites-enabled/