FROM node:18.3.0-alpine3.14

# Necessary for ARM platform
RUN apt -y update
RUN apt -y install python3

COPY signFeed/package.json signFeed/yarn.lock signFeed/signfeed-cli.js /root/signFeed/
WORKDIR /root/signFeed
RUN yarn

RUN chmod a+x /root

RUN mkdir /private
VOLUME /private
# EXPOSE 1633
