FROM ubuntu:22.10

RUN apt -y update
RUN apt -y install curl gcc libssl-dev pkgconf

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN /root/.cargo/bin/rustup default 1.61.0

COPY proxy/src /root/proxy/src
COPY proxy/Cargo.toml proxy/Cargo.lock /root/proxy/Cargo.toml /root/proxy/
WORKDIR /root/proxy
RUN rm -rf target
RUN /root/.cargo/bin/cargo build --release
RUN chmod a+x /root

ENV RUST_LOG=
