FROM ubuntu:22.10

RUN apt -y update && apt -y install curl gcc

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN /root/.cargo/bin/rustup default 1.61.0

COPY preparer/src /root/preparer/src
COPY preparer/Cargo.toml preparer/Cargo.lock /root/preparer/
WORKDIR /root/preparer
RUN /root/.cargo/bin/cargo build --release
RUN chmod a+x /root

ENV RUST_LOG=

VOLUME /volume
