FROM ubuntu:22.10

RUN apt -y update
RUN apt -y install curl gcc

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN $HOME/.cargo/bin/rustup default 1.61.0

COPY brotler ./
WORKDIR brotler
RUN $HOME/.cargo/bin/cargo build --release